"""A-Stock Promotion MVP strategy engine."""

from .admin import StrategyRecord, StrategyRegistry, StrategyRegistryError
from .ai_assistant import (
    AIAssistantError,
    AIParseResult,
    explain_strategy,
    parse_prompt,
    summarize_results,
)
from .community import Comment, CommunityError, CommunityHub, SharedStrategy
from .membership import (
    DEFAULT_BENEFITS,
    MarketplaceOrder,
    MembershipError,
    MembershipService,
    TierBenefits,
    UserMembership,
)
from .backtesting import (
    BacktestConfig,
    BacktestEngine,
    BacktestResult,
    PriceBar,
    RebalanceEvent,
    constant_metrics_provider,
    time_series_metrics_provider,
    to_price_bars,
)
from .data_sources import (
    FundamentalProvider,
    FundamentalSnapshot,
    SampleFundamentalProvider,
    SampleSentimentProvider,
    SentimentProvider,
    SentimentSnapshot,
)
from .etf_pool import (
    ETFFeatureAggregator,
    ETFListing,
    ETFPool,
    ETFProvider,
    ETFSnapshot,
    SampleETFProvider,
    sample_etf_pool,
)
from .features import FeatureAggregator, PriceHistory, compute_technical_metrics
from .indicators import (
    BollingerPoint,
    KDJPoint,
    MACDPoint,
    bollinger_bands,
    exponential_moving_average,
    kdj,
    ma_trend_score,
    macd,
    relative_strength_index,
    simple_moving_average,
    volume_ratio,
)
from .leaderboards import Leaderboard, LeaderboardBuilder, LeaderboardEntry
from .models import SelectionResult, StockMetrics, StrategyProfile, StrategyRule
from .optimization import (
    GridSearchOptimizer,
    OptimizationReport,
    OptimizationTrial,
    WalkForwardReport,
    expand_grid,
    score_calmar,
    score_sharpe,
    score_total_return,
)
from .portfolio import (
    Holding,
    RebalancePlan,
    RebalanceTrade,
    build_rebalance_plan,
    compute_target_weights,
    plan_from_selection,
)
from .risk_metrics import (
    historical_var,
    max_drawdown,
    sharpe_ratio,
    to_returns,
    volatility,
)
from .selection_engine import SelectionEngine
from .stock_pool import StockListing, StockPool, sample_stock_pool
from .strategies import (
    default_etf_strategy,
    default_stock_strategy,
    list_builtin_strategies,
)

__all__ = [
    "AIAssistantError",
    "AIParseResult",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestResult",
    "BollingerPoint",
    "Comment",
    "CommunityError",
    "CommunityHub",
    "DEFAULT_BENEFITS",
    "ETFFeatureAggregator",
    "ETFListing",
    "ETFPool",
    "ETFProvider",
    "ETFSnapshot",
    "FeatureAggregator",
    "FundamentalProvider",
    "FundamentalSnapshot",
    "GridSearchOptimizer",
    "Holding",
    "KDJPoint",
    "Leaderboard",
    "LeaderboardBuilder",
    "LeaderboardEntry",
    "MACDPoint",
    "MarketplaceOrder",
    "MembershipError",
    "MembershipService",
    "OptimizationReport",
    "OptimizationTrial",
    "PriceBar",
    "PriceHistory",
    "RebalanceEvent",
    "RebalancePlan",
    "RebalanceTrade",
    "SampleETFProvider",
    "SampleFundamentalProvider",
    "SampleSentimentProvider",
    "SelectionEngine",
    "SelectionResult",
    "SentimentProvider",
    "SentimentSnapshot",
    "SharedStrategy",
    "StockListing",
    "StockMetrics",
    "StockPool",
    "StrategyProfile",
    "StrategyRecord",
    "StrategyRegistry",
    "StrategyRegistryError",
    "StrategyRule",
    "TierBenefits",
    "UserMembership",
    "WalkForwardReport",
    "bollinger_bands",
    "build_rebalance_plan",
    "compute_target_weights",
    "compute_technical_metrics",
    "constant_metrics_provider",
    "default_etf_strategy",
    "default_stock_strategy",
    "expand_grid",
    "explain_strategy",
    "exponential_moving_average",
    "historical_var",
    "kdj",
    "list_builtin_strategies",
    "ma_trend_score",
    "macd",
    "max_drawdown",
    "parse_prompt",
    "plan_from_selection",
    "relative_strength_index",
    "sample_etf_pool",
    "sample_stock_pool",
    "score_calmar",
    "score_sharpe",
    "score_total_return",
    "sharpe_ratio",
    "simple_moving_average",
    "summarize_results",
    "time_series_metrics_provider",
    "to_price_bars",
    "to_returns",
    "volatility",
    "volume_ratio",
]
