"""A-Stock Promotion MVP strategy engine."""

from .backtesting import (
    BacktestConfig,
    BacktestEngine,
    BacktestResult,
    PriceBar,
    RebalanceEvent,
    constant_metrics_provider,
    time_series_metrics_provider,
    to_price_bars,
)
from .data_sources import (
    FundamentalProvider,
    FundamentalSnapshot,
    SampleFundamentalProvider,
    SampleSentimentProvider,
    SentimentProvider,
    SentimentSnapshot,
)
from .features import FeatureAggregator, PriceHistory, compute_technical_metrics
from .indicators import (
    BollingerPoint,
    KDJPoint,
    MACDPoint,
    bollinger_bands,
    exponential_moving_average,
    kdj,
    ma_trend_score,
    macd,
    relative_strength_index,
    simple_moving_average,
    volume_ratio,
)
from .models import SelectionResult, StockMetrics, StrategyProfile, StrategyRule
from .optimization import (
    GridSearchOptimizer,
    OptimizationReport,
    OptimizationTrial,
    WalkForwardReport,
    expand_grid,
    score_calmar,
    score_sharpe,
    score_total_return,
)
from .risk_metrics import (
    historical_var,
    max_drawdown,
    sharpe_ratio,
    to_returns,
    volatility,
)
from .selection_engine import SelectionEngine
from .stock_pool import StockListing, StockPool, sample_stock_pool
from .strategies import (
    default_etf_strategy,
    default_stock_strategy,
    list_builtin_strategies,
)

__all__ = [
    "BacktestConfig",
    "BacktestEngine",
    "BacktestResult",
    "BollingerPoint",
    "FeatureAggregator",
    "FundamentalProvider",
    "FundamentalSnapshot",
    "GridSearchOptimizer",
    "KDJPoint",
    "MACDPoint",
    "OptimizationReport",
    "OptimizationTrial",
    "PriceBar",
    "PriceHistory",
    "RebalanceEvent",
    "SampleFundamentalProvider",
    "SampleSentimentProvider",
    "SelectionEngine",
    "SelectionResult",
    "SentimentProvider",
    "SentimentSnapshot",
    "StockListing",
    "StockMetrics",
    "StockPool",
    "StrategyProfile",
    "StrategyRule",
    "WalkForwardReport",
    "bollinger_bands",
    "compute_technical_metrics",
    "constant_metrics_provider",
    "default_etf_strategy",
    "default_stock_strategy",
    "expand_grid",
    "exponential_moving_average",
    "historical_var",
    "kdj",
    "list_builtin_strategies",
    "ma_trend_score",
    "macd",
    "max_drawdown",
    "relative_strength_index",
    "sample_stock_pool",
    "score_calmar",
    "score_sharpe",
    "score_total_return",
    "sharpe_ratio",
    "simple_moving_average",
    "time_series_metrics_provider",
    "to_price_bars",
    "to_returns",
    "volatility",
    "volume_ratio",
]
